name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: 
      - self-hosted
      - leo-work-runner
    steps:
      - name: Display the path
        run: start d:leo_go_api\leo_go_api.exe
        shell: cmd
