name: Go
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: 
      - self-hosted
      - leo-work-runner
    steps:        
      - name: Display the path
        run: echo 123
        shell: cmd
