name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: 
      - self-hosted
      - leo-work-runner
    steps:
      - uses: actions/checkout@v3

      - name: Display the path
        run: |
          ls
          leo_go_api.exe
        shell: cmd
